name: Build & push to GHCR

on:
  push:
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve latest tag
        id: tag
        run: ./find_latest_tag.sh
        env:
          REPOSITORY: https://git.sr.ht/~gsthnz/satellite
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            SATELLITE_VERSION=${{ steps.tag.outputs.tag }}
          tags: |
            ghcr.io/tdemin/docker-satellite:latest
            ghcr.io/tdemin/docker-satellite:${{ steps.tag.outputs.tag }}
